GET localhost/students?page=1&size=2

###

POST localhost/students
Content-Type: application/json

{
  "firstName": "Новый студент - имя",
  "lastName": "Новый студент - фамилия"
}

###

PUT localhost/students/2
Content-Type: application/json

{
  "firstName": "Марсель",
  "lastName": "Сидиков"
}

###

DELETE localhost/students/2

###

POST localhost/students/7/courses
Content-Type: application/json

{
  "id": 1
}